/// Flutter icons BottomBar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomBar
///      fonts:
///       - asset: fonts/BottomBar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBar {
  BottomBar._();

  static const _kFontFam = 'BottomBar';
  static const _kFontPkg = null;

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlist = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
